// vuejs/src/pages/home.vue
<template>
    <div>
        <div class="rounded mt-5">
            <p>
                This is pinia count
            </p>
            <p class="mt-3 flex justify-around text-xl">
                <button @click="mainStore.count++">+</button>
                <button @click="mainStore.count--">-</button>
                <button @click="mainStore.$reset">o</button>
            </p>
            <p class="text-center text-3xl mt-3">{{ mainStore.count }}</p>
        </div>

    </div>
</template>
<script setup lang='ts'>
import { useMainStore } from '@/store';
const mainStore = useMainStore()
</script>

// reactjs/src/pages/home.tsx
import { useState } from "react";

export default function Home() {
  const [count, setCount] = useState(0);
  return (
    <div>
      <div className="mt-5 rounded">
        <p>This is state count</p>
        <p className="mt-3 flex justify-around text-xl">
          <button onClick={() => setCount(count + 1)}>+</button>
          <button onClick={() => setCount(count - 1)}>-</button>
          <button onClick={() => setCount(0)}>o</button>
        </p>
        <p className="mt-3 text-center text-3xl">{count}</p>
      </div>
    </div>
  );
}
